### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by papandreou**
An excuse to play around with the upcoming unexpected-snapshot :)

### CODE REVIEW

**Comment by papandreou** [comment]
Maybe we could use something like that `` unindent`...` `` trick that @gustavnikolaj has used before. We could just say that iff the string starts with newline and at least one space, we just unindent it before comparing the subject to it.

**Comment by gustavnikolaj** [comment]
I use unindent all the time for comparing serialized strings - error messages, html etc. 

https://github.com/gustavnikolaj/string-utils/blob/master/README.md#deindent

It should do exactly what you describe above @papandreou.

**Comment by sunesimonsen** [comment]
I like the idea of using unindent as it makes it more explicit.

**Comment by papandreou** [comment]
@gustavnikolaj, thanks! I guess we'd need to use it from within unexpected-snapshot as we can't really assume that the `deindent` function is available.

Luckily, it seems like we can easily use it without a template string:

```js
> require('@gustavnikolaj/string-utils').deindent(['\n    foo\n    bar'])
'foo\nbar'
```

**Comment by gustavnikolaj** [comment]
I would not mind adding support for non-template use.

I generally prefer the explicitness that the template-use gives. It’s a presentational concern of sorts and thus I feel it fits most natural as a sort of annotation to the string. 

But even then, I do see the appeal of doing it automatically in this case.

Maybe you could re-export a modified `deindent` as `snapshot` in the module?

```js
expect(
  foo, 
  ‘to match’,
  snapshot`
    bar
  `
```

The template string method`snapshot` would return an identifiable object that is matched by a type. This could support both the automagic and the explicit approach through different assertions:

- `<string> to match <SnapshotString>`
- `<string> to match snapshot <string>`

**Comment by sunesimonsen** [comment]
The more I think about this issue I think we should just build it into the assertion. It will yield the wanted result 99% of the time without any ceremony.

**Comment by gustavnikolaj** [comment]
I just released version 1.3.0 of `@gustavnikolaj/string-utils` that allows usage such as this:

```js
deindent(`
  foo bar
`); // => 'foo bar'
```

**Comment by papandreou** [comment]
I changed it so it always injects the snapshot as a multiline template string now. What do you think?

**Comment by sunesimonsen** [comment]
@papandreou I think it looks absolutely awesome 👌💪

**Comment by papandreou** [comment]
🤗

**Comment by papandreou** [comment]
@sunesimonsen, could you enable Travis and coveralls for this repo?

I guess we're not in a hurry to merge this, but theoretically we could just land it on master and play with it there.

**Comment by papandreou** [comment]
Switched to the released version of unexpected-snapshot now. This should be ready to merge now.

**Comment by sunesimonsen** [comment]
I'll turn on travis when I get in the office.

**Pull request merged**
