### PR TITLE
Also recognize github's new <PR title> (#1234) syntax

### PR DESCRIPTION
**Pull request by Munter**

### CODE REVIEW

**Comment by papandreou** [comment]
Argh, needs `prettier --fix '**/*.js'`

**Comment by sunesimonsen** [comment]
@Munter this seems great, can you fix the code formatting :-)

**Comment by papandreou** [comment]
I think I wrote this on Peter's computer :see_no_evil:

I'll fix it up, one sec.

**Comment by papandreou** [comment]
Released in 1.7.0

**Pull request merged**
