### PR TITLE
Fix duplicated authors

### PR DESCRIPTION
**Pull request by sunesimonsen**

### CODE REVIEW

**Comment by sunesimonsen** [comment]
@papandreou I'm getting this error when I'm trying to update the snapshots:

```
  1) "after all" hook in "{root}":
     TypeError: prettier.getFileInfo.sync is not a function
```

**Comment by papandreou** [comment]
> @papandreou I'm getting this error when I'm trying to update the snapshots:
> 
> ```
>   1) "after all" hook in "{root}":
>      TypeError: prettier.getFileInfo.sync is not a function
> ```

Hmm, maybe there was a backwards-incompatible change in `prettier` 3.x or something. I'll take a look :eyes:

**Comment by papandreou** [comment]
Yeah, looks like `require('prettier').getFileInfo.sync` disappeared between 2.x and 3.x, although `require('prettier').getFileInfo` is still there.

**Comment by papandreou** [comment]
They do mention it in the release notes for 3.0.0 [here](https://prettier.io/blog/2023/07/05/3.0.0.html#change-public-apis-to-asynchronous-12574httpsgithubcomprettierprettierpull12574-12788httpsgithubcomprettierprettierpull12788-12790httpsgithubcomprettierprettierpull12790-13265httpsgithubcomprettierprettierpull13265-by-fiskerhttpsgithubcomfisker)

**Comment by papandreou** [comment]
That's a bit of a challenge for [`prettyMaybe.sync`](https://github.com/papandreou/pretty-maybe/blob/0190e6298f5f5c86a0b7ff4190d8c224da3d6457/lib/pretty-maybe.js#L51-L54), which is being used by `unexpected-snapshot` in a sync context [here](https://github.com/unexpectedjs/unexpected-snapshot/blob/164bcc6ac63eaa6c80394dac29f7e04cfd7a2761/lib/applyFixes.js#L257-L259) :thinking:

**Comment by papandreou** [comment]
Published [a fix](https://github.com/unexpectedjs/unexpected-snapshot/pull/166) in unexpected-snapshot 2.2.0 :relieved:

**Comment by papandreou** [comment]
Also published pretty-maybe 1.2.2, which [throws a better error](https://github.com/papandreou/pretty-maybe/commit/a9bd9d6fdb86941adae76d195886c47b6c693faa) when these `sync` functions are missing.

**Comment by sunesimonsen** [comment]
@papandreou thanks a lot - it was not my intension to put you to this much work 😅

**Pull request merged**
