### PR TITLE
Add a remote cli argument

### PR DESCRIPTION
**Pull request by NKjoep**
Hi 👋 

I thought of de-hardcoding the remote name.
So I've added a remote option to this nice changelog generator :) 

Have a look! 

Cheers 🐝

### CODE REVIEW

**Comment by sunesimonsen** [comment]
@NKjoep sorry that I newer reacted to your PR. I was somehow not watching this repo, so I haven't seen it before now. I'll get back to your in a few days. My first reaction is this makes a lot of sense and that we probably want to use a command line parser like https://github.com/sindresorhus/meow.

**Comment by NKjoep** [comment]
Hi @sunesimonsen thank you for replying :) I can have a look to meow, it should be pretty straightforward.

Do you want meanwhile merge this? I will take some time for me to do it, I came back to work this week :)

**Comment by NKjoep** [comment]
@sunesimonsen done. what do you think?

**Comment by NKjoep** [comment]
Thank you for the new release! I appreciate it! 🎉 

To answer your question, We work with PRs and forks and most of the time the main remote is not named _origin_ but _upstream_.

So in my case, I need to generate the changelog pointing to a different remote `offline-github-changelog --remote=upstream` in order to get the right list of changes. 😉

**Comment by sunesimonsen** [comment]
Awesome thanks for the explanation.

**Pull request merged**
